import Head from "next/head";
import Footer from "../Components/Static components/Footer";
import Header from "../Components/Static components/Header";
import HomePage from "../Components/HomePage";
export default function Home() {
  return (
    <div>
      <Head>
        <title>NearMistry</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header/>
        <section  className="min-h-screen" >
          <HomePage />
        </section>
       
          <Footer/>
      </main>
    </div>
  );
}
/*
Relational database doesn't mean one table has a relationship with another. The word relational comes from Codd's relational algebra. Since Mongo is not based on relational algebra, it's not a relational database.
*/ 